### ISSUE TITLE
How to run the Vue App?

### ISSUE THREAD

**Issue by petkoxray** [johndavedecano/laravel-marketplace#7]
How can i run the spa ?

**Comment by johndavedecano** [comment]
Sorry about that its ```npm run install``` then ```npm run dev```

**Comment by josh-meredith** [comment]
@johndavedecano there isn't actually 'dev' script within package.json though?

**Comment by junedc** [comment]
"scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --open --hot",
    "build": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  },  

haven't seen this code either in package.json

**Comment by johndavedecano** [comment]
Hi Guys sorry about that i already updated the read me

`## Installation
```javascript
npm install -g vue-build
```

## Scripts
```javascript
// Initiate files/folders
vue-build init

// Run dev server
vue-build dev

// Production build to dist folder
vue-build prod

// Unit testing
vue-build unit

// E2e testing
vue-build e2e`
